tap "mongodb/brew"
tap "freight-hub/internal"
tap "homebrew/services"

brew "coreutils"
brew "curl"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "helix"
brew "jq"
brew "lazygit"
brew "neovim"
brew "nmap"
brew "ripgrep"
brew "saml2aws"
brew "sops"
brew "starship"
brew "stow"
brew "telnet"
brew "tmux"
brew "wget"
brew "yamlfmt"
brew "yazi"
brew "yt-dlp"
brew "zoxide"

brew "freight-hub/internal/forto-cli"
brew "mongodb/brew/mongodb-database-tools"

cask "docker"
cask "alt-tab"
cask "font-symbols-only-nerd-font"
