[tools]
bat = "latest"
bottom = "latest"
"cargo:jj-cli" = "latest"
"cargo:lazyjj" = "latest"
claude-code = "latest"
fnox = "latest"
gcloud = "latest"
lsd = "latest"
node = "22"
python = "latest"
rust = "latest"
yarn = "latest"
