[shell_alias]
ls = "lsd"
la = "lsd -A1 --blocks permission,date,git,size,name"
cat = "bat"
cd = "z"
top = "btm"
du = "dust"

[tools]
age = "latest"
"aqua:YS-L/csvlens" = "latest"
"aqua:auth0/auth0-cli" = "latest"
"aqua:github/copilot-cli" = "latest"
"aqua:jj" = "latest"
aws = { version = "latest", symlink_bins = "true" }
bat = "latest"
bottom = "latest"
"cargo:lazyjj" = "latest"
delta = "latest"
fnox = "latest"
gcloud = "latest"
kubectl = "latest"
lsd = "latest"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
python = "latest"
restic = "latest"
rust = "latest"
shellcheck = "latest"
yarn = "latest"
yazi = "latest"
yq = "latest"
zig = "master"
