[tools]
"aqua:jj" = "latest"
bat = "latest"
bottom = "latest"
"cargo:lazyjj" = "latest"
fnox = "latest"
gcloud = "latest"
lsd = "latest"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
python = "latest"
rust = "latest"
yarn = "latest"
